version: "3.8"

services:
  portal:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./portal:/usr/share/nginx/html

  mogoso:
    build: ./games/mogoso
    ports:
      - "3001:3001"
